package scan

import (
	"archive/zip"
	"bytes"
	"strings"
	"testing"

	"github.com/ziozzang/bongsu-scanner/internal/purl"
)

// fuzzZip builds an archive from name -> content pairs; nil content is a
// directory entry. Errors cannot happen for in-memory writes.
func fuzzZip(entries map[string][]byte, order []string) []byte {
	var b bytes.Buffer
	zw := zip.NewWriter(&b)
	for _, name := range order {
		data := entries[name]
		if data == nil {
			_, _ = zw.Create(name)
			continue
		}
		w, _ := zw.Create(name)
		_, _ = w.Write(data)
	}
	_ = zw.Close()
	return b.Bytes()
}

const fuzzManifest = "Manifest-Version: 1.0\r\nCreated-By: Maven JAR Plugin 3.3.0\r\nBuild-Jdk-Spec: 17\r\nImplementation-Title: Apache Commons Lang\r\nImplementation-Version: 3.12.0\r\nImplementation-Vendor-Id: org.apache.commons\r\nBundle-SymbolicName: org.apache.commons.lang3\r\nBundle-Version: 3.12.0\r\nAutomatic-Module-Name: org.apache.commons.lang3\r\nLong-Header: first part of a very long value that wraps onto\r\n  the next line\r\n\r\nName: org/apache/commons/lang3/\r\nImplementation-Version: 9.9.9\r\n"

func FuzzJavaArchive(f *testing.F) {
	pom := []byte("#Generated by Maven\nversion=3.12.0\ngroupId=org.apache.commons\nartifactId=commons-lang3\n")
	inner := fuzzZip(map[string][]byte{
		"META-INF/MANIFEST.MF":      []byte("Manifest-Version: 1.0\r\nImplementation-Version: 2.0.1\r\nImplementation-Vendor-Id: com.example\r\n"),
		"com/example/inner/A.class": []byte{0xca, 0xfe, 0xba, 0xbe},
	}, []string{"META-INF/MANIFEST.MF", "com/example/inner/A.class"})
	f.Add(fuzzZip(map[string][]byte{
		"META-INF/":            nil,
		"META-INF/MANIFEST.MF": []byte(fuzzManifest),
		"META-INF/maven/org.apache.commons/commons-lang3/pom.properties": pom,
		"org/apache/commons/lang3/StringUtils.class":                     []byte{0xca, 0xfe, 0xba, 0xbe},
		"BOOT-INF/lib/inner-2.0.1.jar":                                   inner,
	}, []string{"META-INF/", "META-INF/MANIFEST.MF", "META-INF/maven/org.apache.commons/commons-lang3/pom.properties", "org/apache/commons/lang3/StringUtils.class", "BOOT-INF/lib/inner-2.0.1.jar"}))
	f.Add(fuzzZip(map[string][]byte{
		"META-INF/MANIFEST.MF": []byte("Manifest-Version: 1.0\r\nImplementation-Title: OpenJDK Runtime Environment\r\nImplementation-Version: 17.0.9\r\nImplementation-Vendor: Eclipse Adoptium\r\n"),
		"release":              []byte("IMPLEMENTOR=\"Eclipse Adoptium\"\nJAVA_VERSION=\"17.0.9\"\nJAVA_VENDOR=\"Eclipse Adoptium\"\n"),
	}, []string{"META-INF/MANIFEST.MF", "release"}))
	f.Add(fuzzZip(map[string][]byte{
		"META-INF/MANIFEST.MF":             []byte("Manifest-Version: 1.0\r\nBundle-SymbolicName: org.apache.tomcat-catalina;singleton:=true\r\nImplementation-Title: Apache Tomcat\r\nImplementation-Version: 10.1.19\r\n"),
		"org/apache/catalina/Server.class": {},
	}, []string{"META-INF/MANIFEST.MF", "org/apache/catalina/Server.class"}))
	f.Add([]byte("PK\x03\x04garbage"))
	f.Add([]byte{})
	f.Fuzz(func(t *testing.T, data []byte) {
		for _, name := range []string{"usr/share/java/commons-lang3-3.12.0.jar", "app.war", "lib/catalina.jar"} {
			var pkgs []Package
			skipped, failures := scanJavaArchive(bytes.NewReader(data), int64(len(data)), File{Path: name, Size: int64(len(data))}, func(p Package) { pkgs = append(pkgs, p) })
			if skipped < 0 || failures < 0 {
				t.Fatalf("negative counters %d %d", skipped, failures)
			}
			for _, p := range pkgs {
				if !javaCoordinatePart(p.Name) || !javaCoordinatePart(p.Version) {
					t.Fatalf("java package with blank coordinates: %+v", p)
				}
				if p.Type != "maven" && p.Type != "generic" {
					t.Fatalf("unexpected java package type %+v", p)
				}
			}
			out, _ := catalog([]File{{Path: name, Data: data, Size: int64(len(data))}}, nil)
			for _, p := range out {
				if p.PURL == "" {
					t.Fatalf("java package without purl: %+v", p)
				}
				if _, err := purl.Parse(p.PURL); err != nil {
					t.Fatalf("java purl %q: %v", p.PURL, err)
				}
			}
		}
	})
}

func FuzzJavaManifest(f *testing.F) {
	f.Add([]byte(fuzzManifest))
	f.Add([]byte("Manifest-Version: 1.0\nImplementation-Version: 1.0\n continued\n\nName: x\n"))
	f.Add([]byte(" leading continuation\nNoColon\n:empty\n"))
	f.Add([]byte("IMPLEMENTOR=\"Eclipse Adoptium\"\nJAVA_VERSION=\"17.0.9\"\nJAVA_VENDOR=\"Eclipse Adoptium\"\n"))
	f.Fuzz(func(t *testing.T, data []byte) {
		v := javaManifest(data)
		for k := range v {
			if k != strings.ToLower(k) || strings.TrimSpace(k) != k {
				t.Fatalf("manifest key %q not normalized", k)
			}
		}
		_ = javaManifestGroup(v)
		_ = javaTomcatArtifact("catalina", "org.apache.catalina", v)
		if p, ok := javaReleasePackage(data, "jdk!release", ""); ok {
			if p.Version == "" || p.Version[0] < '0' || p.Version[0] > '9' {
				t.Fatalf("release package with bad version: %+v", p)
			}
		}
		name, version := archiveNameVersion(string(data))
		if version != "" && (version[0] < '0' || version[0] > '9') {
			t.Fatalf("archiveNameVersion(%q) = %q, %q", data, name, version)
		}
	})
}
